### ISSUE TITLE
User delegates no longer working in GAM > 3.71?

### ISSUE THREAD

**Issue by jamenlang** [jay0lee/GAM#493]
I hate to bother anyone as 3.71 is working for me, but for clarification

I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. run gam user it@redacted.gov show delegates
2. get an error and no delegates
3.

Expected outcome (what are you trying to do?):
view delegates for an email address with delegates

Actual outcome (what errors or bad behavior do you see instead?):
gam user it@redacted.gov show delegates
Traceback (most recent call last):
  File "gam.py", line 11190, in <module>
  File "gam.py", line 10873, in ProcessGAMCommand
  File "gam.py", line 1135, in printShowDelegates
AttributeError: 'Resource' object has no attribute 'delegates'
Failed to execute script gam

**Comment by jay0lee** [comment]
The first step is always upgrading to the latest version. GAM 3.71 is very old and not supported.
