### ISSUE TITLE
ERROR: User unknown@unknown: invalid_grant: Invalid email or User ID

### ISSUE THREAD

**Issue by Shotster** [jay0lee/GAM#687]
When I attempt to grant editing privileges to a user with the latest version of GAM on a Mac running Mac OS 10.12.6, I get the following:

```
MyMac:~ clover$ gam calendar <calendarid>@group.calendar.google.com add editor user@domain.org

ERROR: User unknown@unknown: invalid_grant: Invalid email or User ID
Traceback (most recent call last):
  File "gam.py", line 12881, in <module>
  File "gam.py", line 12455, in ProcessGAMCommand
  File "gam.py", line 3361, in doCalendarAddACL
AttributeError: 'NoneType' object has no attribute 'acl'
[25958] Failed to execute script gam
MyMac:~ clover$
```

It most definitely is a valid user. I've been using GAM for a while (though only sporadically) and have never had an issue until now, so I'm stumped.

I do have multiple Google accounts. Could GAM possibly be attempting to execute the command using the wrong account? Is there a way to force it to use a specific account?

**EDIT**: I can "show calendars" for that same user without a problem. 😕

**Comment by jay0lee** [comment]
This should be fixed in GAM 4.40, please upgrade.

https://git.io/gam-releases

**Comment by Shotster** [comment]
Unfortunately, no go. It just happened again today using 4.40. The user is definitely a valid. Like the other instance, though, they had been recently added. Don't know if that helps.

```
ERROR: User unknown@unknown: invalid_grant: Invalid email or User ID
Traceback (most recent call last):
  File "gam.py", line 12881, in <module>
  File "gam.py", line 12455, in ProcessGAMCommand
  File "gam.py", line 3361, in doCalendarAddACL
AttributeError: 'NoneType' object has no attribute 'acl'
[57294] Failed to execute script gam
```

**Comment by jay0lee** [comment]
You also need to recreate the auth token. Run;

gam oauth revoke
gam info domain

**Comment by Shotster** [comment]
Not only that, but I was able to add calendars to the list of calendars in that user’s account. It was only when attempting to grant them editing privileges at the error arose.

**Comment by Shotster** [comment]
@taers232c, I'm executing the following...

`gam calendar domain.com_abc123etc@group.calendar.google.com add editor user@domain.com`

**Comment by jay0lee** [comment]
Did you revoke and re-authorize as I mentioned above? That should resolve the Unknown issue.

**Comment by Shotster** [comment]
@jay0lee, I tried, but it keeps displaying the same prompt to choose the scopes. I type "s" and then return, and it redisplays the prompt. ☹️ Then I type "e" to exit and get the following:

```
Please enter 0-23[a|r] or s|u|e|c: e
Traceback (most recent call last):
  File "gam.py", line 12881, in <module>
  File "gam.py", line 12270, in ProcessGAMCommand
  File "gam.py", line 1633, in doGetDomainInfo
  File "gam.py", line 1655, in doGetCustomerInfo
  File "gam.py", line 887, in buildGAPIObject
AttributeError: 'NoneType' object has no attribute 'user_agent'
[66609] Failed to execute script gam
```

**Comment by jay0lee** [comment]
You probably don't want to select all scopes, just leave it at default. Then choose c to continue to authorization, not e.

**Comment by Shotster** [comment]
Re-authenticating seems to have solved the problem. Thank you!

**Comment by henkbaert** [comment]
Using gam v4.82, this problem is back!

`gam calendar domain.com_abc123etc@group.calendar.google.com add editor user@domain.com`
and
`gam calendar domain.com_abc123etc@group.calendar.google.com showacl`

Both return the following error:
`ERROR: Authentication Token Error - ('invalid_grant: Invalid email or User ID', '{\n  "error": "invalid_grant",\n  "error_description": "Invalid email or User ID"\n}')`

I did a revoke and authorize as described here; but the problem remains.

Previous version of gam was v4.40 and there the problem did not occur.
2 of our admins updated their gam to v4.82, both experience the same problem.

Any advice?

**Comment by jay0lee** [comment]
Send unlikely that this is an issue for 4.82 but works in 4.40 but you should be able to download 4.40, install it into another directory and confirm whether or not it works.

Are all these users super admins?

**Comment by henkbaert** [comment]
Installed 4.40 in second directory and tried:
`gam calendar domain.com_abc123etc@group.calendar.google.com showacl`

Returned correct info:
```
Calendar: domain.net_123456789@resource.calendar.google.com, ACL: (Scope: user:domain.net_123456789@resource.calendar.google.com, Role: owner) (1/2)
Calendar: domain.net_123456789@resource.calendar.google.com, ACL: (Scope: group:group_name@persgroep.net, Role: writer) (2/2)
```

All users who tried it are SuperAdmins.

One of our external support engineers tried all version starting from 4.40 and provides this info:
- same issue in domain from other client
- version up until 4.72 are working fine
- version 4.80, 4.81 and 4.82 have problems

Hope this helps pinpointing the problem

**Comment by jay0lee** [comment]
Are you copying the same oauth2client.json file between GAM versions?

**Comment by henkbaert** [comment]
indeed; copied
- client_secrets.json
- LICENSE
- oauth2.txt
- oauth2service.json

**Comment by jay0lee** [comment]
Can you post the results of:

gam user <non admin email address> check serviceaccount

?

**Comment by henkbaert** [comment]
```
User: non.admin@persgroep.net
 Scope: https://mail.google.com/                                     PASS
 Scope: https://www.googleapis.com/auth/activity                     PASS
 Scope: https://www.googleapis.com/auth/calendar                     PASS
 Scope: https://www.googleapis.com/auth/drive                        PASS
 Scope: https://www.googleapis.com/auth/gmail.settings.basic         PASS
 Scope: https://www.googleapis.com/auth/gmail.settings.sharing       PASS
 Scope: https://www.googleapis.com/auth/plus.me                      FAIL

ERROR: Some scopes failed! Please go to:

https://admin.google.com/domain.net/AdminHome?#OGX:ManageOauthClients

and grant Client name:

1234567890

Access to scopes:

https://mail.google.com/,
https://www.googleapis.com/auth/activity,
https://www.googleapis.com/auth/calendar,
https://www.googleapis.com/auth/drive,
https://www.googleapis.com/auth/gmail.settings.basic,
https://www.googleapis.com/auth/gmail.settings.sharing,
https://www.googleapis.com/auth/plus.me
```

**Comment by henkbaert** [comment]
output from v4.82
```
User: non.admin@persgroep.net
 Scope: https://mail.google.com/                                     PASS
 Scope: https://www.googleapis.com/auth/activity                     PASS
 Scope: https://www.googleapis.com/auth/apps.alerts                  PASS
 Scope: https://www.googleapis.com/auth/calendar                     PASS
 Scope: https://www.googleapis.com/auth/drive                        PASS
 Scope: https://www.googleapis.com/auth/gmail.settings.basic         PASS
 Scope: https://www.googleapis.com/auth/gmail.settings.sharing       PASS
 Scope: https://www.googleapis.com/auth/spreadsheets                 PASS

All scopes passed!
Service account 1234567890 is fully authorized.
```

**Comment by henkbaert** [comment]
Hello there,

were you able to reproduce the problem?

**Comment by lm2807** [comment]
This appears to be fixed in 4.83, at least for me.
